### ISSUE TITLE
not working on MacOS Big Sur

### ISSUE THREAD

**Issue by gnai** [cuongndc9/free-spotify#4]

**Comment by cuongtk8** [comment]
@Gnai, please provide your detailed information. Thanks!!

**Comment by gnai** [comment]
just downloaded with the command, and it's still giving me the audio ads

**Comment by cuongtk8** [comment]
@Gnai please try again, I resolved this issue!!

```sh
sudo sh -c "$(curl -sSL https://raw.githubusercontent.com/kimcuong060498/free-spotify/master/install.sh)"
```

**Comment by gnai** [comment]
working! thank you! what was the issue? 
Do you plan on doing this for the app on macOS btw ? I found some workarounds for it but not very practical with some third party apps.

**Comment by cuongtk8** [comment]
- The issue is an outdated URL.
- I don't have a plan to build an application on macOS. In my opinion, we should pay fees to support Spotify.

@Gnai , thank bro!!
