### ISSUE TITLE
Does not block ads by Spotify about premium.

### ISSUE THREAD

**Issue by AreOlsen** [cuongndc9/free-spotify#5]
Title pretty much explains it, it does not block ads by spotify about spotify premium, all other ads, get blocked tho.

**Comment by cuongtk8** [comment]
@SimonGoBrrr thanks for your issue, please provide your device information

**Comment by cuongtk8** [comment]
This project based on [SpotifyAdBlock](https://github.com/x0uid/SpotifyAdBlock).
You can first-check [here](https://github.com/x0uid/SpotifyAdBlock/issues) issues.

@SimonGoBrrr
